
# Site settings
title: keything 
email: keything@icloud.com
description: > # this means to ignore newlines until "baseurl:"
  Record daily learn.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://keything.com" # the base hostname & protocol for your site
twitter_username: keything 
github_username: keything 

# Build settings
markdown: kramdown
